# Aqui você tem um guia de Sintaxe para o 
# Github Actions:
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
# https://docs.github.com/pt/actions/using-workflows/workflow-syntax-for-github-actions

# Caso tenha dificuldades com a sintaxe de yaml:
# https://learnxinyminutes.com/docs/yaml/ 

# este é o nome do workflow, que aparece no menu 
# "Actions" do seu repositório.
name: Hello world workflow

# O nome das execuções de fluxo de trabalho geradas pelo fluxo de trabalho. 
# O GitHub exibe o nome da execução de fluxo de trabalho na lista de execuções 
# de fluxo de trabalho, na guia "Ações" do repositório. 
# Se run-name for omitido ou for apenas um espaço em branco, o nome da execução 
# será definido como informações específicas do evento para a execução de fluxo 
# de trabalho. Por exemplo, para um fluxo de trabalho disparado por um evento 
# push ou pull_request, ele é definido como a mensagem de commit.
# Esse valor pode incluir expressões e referenciar os contextos github e inputs
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}

# Aqui, podemos ver mais detalhes sobre os contextos.
# Os contextos são uma forma de acessar informações sobre execuções 
# de fluxo de trabalho, variáveis, ambientes dos executores, trabalhos 
# e etapas. Cada contexto é um objeto que contém propriedades, 
# que podem ser cadeia de caracteres ou outros objetos
# https://docs.github.com/pt/actions/learn-github-actions/contexts

# identificação dos eventos. 
# Há uma lista enorme de eventos que 
# podemos usar como trigger.
# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
# https://docs.github.com/pt/actions/using-workflows/events-that-trigger-workflows
on:
# on: [push, fork]
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

# grupo de jobs neste workflow 
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      # actions/checkout se refere ao projeto público
      # (https://github.com/actions/checkout), e o @v2
      # se refere à tag v2, mas pode ser uma tag, um commit 
      # específico, um branch... Qualquer identificador 
      # do git válido. Neste caso, é a action que baixa 
      # o código no ambiente de execução (runner)
      - uses: actions/checkout@v2
      #este é o nome do step
      - name: hello world
        # este é o comando que vai ser executado neste step. 
        # neste caso, ao invés de uma action preexistente 
        # estamos executando um shell command.
        run: echo "Hello world"
        # e este shell command vai ser executado no bash 
        shell: bash

  goodbye:  
    runs-on: ubuntu-latest
    steps:
     - name: goodbye world
       run: echo "Goodbye world"
       shell: bash




